"""V2.1 migration proposals against a frozen synthetic V2.0 bootstrap contract."""

import hashlib
import importlib.util
import json
import os
from pathlib import Path
import shutil
import stat
import subprocess
import sys
import tempfile
import unittest
from unittest import mock


ROOT = Path(__file__).resolve().parents[1]
CLI = ROOT / "plugins/team-engineering-skills/scripts/project-update.py"
STANDARDS = ("ai-usage.md", "coding-output.md", "data-access.md", "security.md")

# Frozen synthetic shape generated by the bootstrap contract at baseline 64d176e.
# It deliberately remains 2.0.0 and does not reuse or relabel the current registry.
V2_REGISTRY = {
    "schema_version": 1,
    "version": "2.0.0",
    "owner": "Synthetic Fixture Owner",
    "standards": {},
    "skills": [
        {
            "name": "synthetic-requirement-helper",
            "version": "1.0.0",
            "owner": "Synthetic Fixture Owner",
            "routes": ["Analyze synthetic requirements"],
            "tree_sha256": "0" * 64,
        }
    ],
}


def load_update_module():
    scripts = str(CLI.parent)
    sys.path.insert(0, scripts)
    try:
        spec = importlib.util.spec_from_file_location("project_update_test", CLI)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module
    finally:
        sys.path.remove(scripts)


def baseline_agents(registry):
    lines = [
        "# Team AI Operating Framework", "", "Release: " + registry["version"], "",
        "Read these local standards before acting:", "",
        *["- .team-ai/standards/" + name for name in sorted(registry["standards"])], "",
        "These instructions are advisory, not a security boundary. Respect higher-priority",
        "client instructions, user authorization and project-specific constraints; stop on conflicts.",
        "Cloud model calls can send code off this computer. Do not read or transmit secrets.", "",
        "## Skill selection", "",
        "Use the smallest relevant set of installed team-engineering-skills skills below.",
        "Read the selected SKILL.md fully and announce the skill and reason before acting.",
        "This table guides the current client; it does not launch or switch AI providers.",
        "If a skill is unavailable, state that clearly and use a safe general fallback.",
        "Never claim a missing skill ran. Match task intent, not only exact keywords.", "",
    ]
    for skill in registry["skills"]:
        lines.append("- " + skill["name"] + ": " + "; ".join(skill["routes"]))
    lines.extend([
        "", "Registry and version evidence: .team-ai/registry.json and .team-ai/release.json.",
        "Feedback is manual and sanitized via GitHub Issues; never upload prompts or code automatically.", "",
    ])
    return "\n".join(lines)


class ProjectUpdateTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.base = Path(self.temporary.name).resolve()
        self.project = self.base / "project"
        self.project.mkdir()
        self.output = self.base / "proposal"
        self.make_frozen_v2_project()

    def make_frozen_v2_project(self):
        snapshot = self.project / ".team-ai"
        standards = snapshot / "standards"
        standards.mkdir(parents=True)
        registry = json.loads(json.dumps(V2_REGISTRY))
        for name in STANDARDS:
            data = ("synthetic-v2-policy:" + name + "\n").encode()
            (standards / name).write_bytes(data)
            registry["standards"][name] = hashlib.sha256(data).hexdigest()
        registry_bytes = (json.dumps(registry, indent=2, sort_keys=True) + "\n").encode()
        (snapshot / "registry.json").write_bytes(registry_bytes)
        evidence = {
            "schema_version": 1,
            "version": "2.0.0",
            "owner": "Synthetic Fixture Owner",
            "sha256": {
                "registry.json": hashlib.sha256(registry_bytes).hexdigest(),
                **{
                    "standards/" + name: hashlib.sha256((standards / name).read_bytes()).hexdigest()
                    for name in STANDARDS
                },
            },
            "provenance": "Explicit local release; hashes detect drift, not publisher authenticity.",
        }
        (snapshot / "release.json").write_text(
            json.dumps(evidence, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        (self.project / "AGENTS.md").write_text(baseline_agents(registry), encoding="utf-8")
        (self.project / "CLAUDE.md").write_text("# Team AI adapter\n\n@AGENTS.md\n", encoding="utf-8")

    def run_cli(self, release=ROOT, output=None, *extra):
        return subprocess.run(
            [
                sys.executable, str(CLI), "--release", str(release),
                "--project", str(self.project), "--output", str(output or self.output), *extra,
            ],
            capture_output=True,
            text=True,
        )

    def project_bytes(self):
        return {
            path.relative_to(self.project).as_posix(): path.read_bytes()
            for path in sorted(self.project.rglob("*")) if path.is_file()
        }

    def test_generates_new_reviewable_proposal_without_mutating_project(self):
        before = self.project_bytes()
        previous_contract = json.loads(
            (self.project / ".team-ai/registry.json").read_text(encoding="utf-8")
        )
        self.assertEqual(previous_contract["version"], "2.0.0")
        result = self.run_cli()
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(self.project_bytes(), before)
        self.assertTrue((self.output / "AGENTS.md").is_file())
        self.assertTrue((self.output / "CLAUDE.md").is_file())
        proposed = json.loads((self.output / ".team-ai/release.json").read_text())
        self.assertEqual(proposed["version"], "2.2.0")
        migration = (self.output / "MIGRATION.md").read_text(encoding="utf-8")
        self.assertIn("2.0.0", migration)
        self.assertIn("2.2.0", migration)
        self.assertIn("manual", migration.casefold())
        self.assertIn("diff", migration.casefold())
        self.assertTrue((self.output / "project-to-proposal.diff").is_file())

    def test_dry_run_validates_but_writes_nothing(self):
        before = self.project_bytes()
        result = self.run_cli(ROOT, self.output, "--dry-run")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertFalse(self.output.exists())
        self.assertEqual(self.project_bytes(), before)
        self.assertIn("no writes", result.stdout.casefold())

    def test_custom_instructions_are_unchanged_and_reported_as_conflicts(self):
        custom = "\n# Project-specific approval: ask the human owner.\n"
        with (self.project / "AGENTS.md").open("a", encoding="utf-8") as stream:
            stream.write(custom)
        before = self.project_bytes()
        result = self.run_cli()
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(self.project_bytes(), before)
        conflicts = (self.output / "CONFLICTS.md").read_text(encoding="utf-8")
        self.assertIn("Project-specific approval", conflicts)
        self.assertIn("manual", conflicts.casefold())

    def test_crlf_only_baseline_does_not_report_a_custom_instruction_conflict(self):
        for name in ("AGENTS.md", "CLAUDE.md"):
            path = self.project / name
            # write_text already emits CRLF on Windows: normalize before conversion
            # so the fixture never accidentally creates CR-CR-LF blank lines.
            normalized = path.read_bytes().replace(b"\r\n", b"\n")
            path.write_bytes(normalized.replace(b"\n", b"\r\n"))
            self.assertNotIn(b"\r\r\n", path.read_bytes())
            self.assertEqual(path.read_bytes().replace(b"\r\n", b"\n"), normalized)
        before = self.project_bytes()

        result = self.run_cli()

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(self.project_bytes(), before)
        self.assertFalse((self.output / "CONFLICTS.md").exists())
        migration = (self.output / "MIGRATION.md").read_text(encoding="utf-8")
        self.assertIn("Custom instruction conflicts detected: 0", migration)

    def test_snapshot_drift_and_tampered_release_are_refused_without_output(self):
        (self.project / ".team-ai/standards/security.md").write_text("drift")
        result = self.run_cli()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("drift", result.stderr.casefold())
        self.assertFalse(self.output.exists())

        shutil.rmtree(self.project)
        self.project.mkdir()
        self.make_frozen_v2_project()
        release = self.base / "release"
        shutil.copytree(ROOT / "plugins/team-engineering-skills", release / "plugins/team-engineering-skills")
        (release / "plugins/team-engineering-skills/standards/security.md").write_text("tampered")
        result = self.run_cli(release)
        self.assertNotEqual(result.returncode, 0)
        self.assertFalse(self.output.exists())

    def test_symlinks_overlaps_and_existing_output_are_refused(self):
        outside = self.base / "outside-agents.md"
        outside.write_text("outside")
        agents = self.project / "AGENTS.md"
        agents.unlink()
        agents.symlink_to(outside)
        result = self.run_cli()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("symlink", result.stderr.casefold())
        self.assertFalse(self.output.exists())

        agents.unlink()
        agents.write_text("restored")
        result = self.run_cli(ROOT, self.project / "proposal")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("overlap", result.stderr.casefold())

        self.output.mkdir()
        sentinel = self.output / "keep.txt"
        sentinel.write_text("keep")
        result = self.run_cli()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("exists", result.stderr.casefold())
        self.assertEqual(sentinel.read_text(), "keep")

    def test_new_output_canonicalizes_its_existing_parent(self):
        module = load_update_module()
        container = self.base / "container"
        container.mkdir()
        lexical = container / ".." / "canonical-proposal"
        self.assertEqual(
            module.safe_new_directory(lexical),
            self.base / "canonical-proposal",
        )

    def test_reparse_point_attribute_on_output_ancestor_is_refused_portably(self):
        module = load_update_module()
        reparse_flag = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
        real_lstat = os.lstat

        def simulated_lstat(path):
            result = real_lstat(path)
            if Path(path) != self.base:
                return result
            return mock.Mock(st_mode=result.st_mode, st_file_attributes=reparse_flag)

        with mock.patch("os.lstat", side_effect=simulated_lstat):
            with self.assertRaisesRegex(ValueError, "reparse|junction"):
                module.safe_new_directory(self.output)

    @unittest.skipUnless(sys.platform == "win32", "requires a live Windows NTFS junction")
    def test_windows_junction_alias_into_project_is_refused_without_writes(self):
        alias = self.base / "project-junction"
        created = subprocess.run(
            ["cmd", "/c", "mklink", "/J", str(alias), str(self.project)],
            capture_output=True,
            text=True,
        )
        self.assertEqual(created.returncode, 0, created.stdout + created.stderr)
        self.addCleanup(lambda: alias.rmdir() if alias.exists() else None)
        actual_output = self.project / "proposal-through-junction"
        result = self.run_cli(ROOT, alias / actual_output.name)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("reparse", result.stderr.casefold())
        self.assertFalse(actual_output.exists())

    def test_inconsistent_and_unsupported_prior_contracts_are_refused(self):
        evidence_path = self.project / ".team-ai/release.json"
        evidence = json.loads(evidence_path.read_text())
        evidence["version"] = "2.0.1"
        evidence_path.write_text(json.dumps(evidence))
        result = self.run_cli()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("inconsistent", result.stderr.casefold())
        self.assertFalse(self.output.exists())

        shutil.rmtree(self.project)
        self.project.mkdir()
        self.make_frozen_v2_project()
        registry_path = self.project / ".team-ai/registry.json"
        registry = json.loads(registry_path.read_text())
        registry["version"] = "1.9.0"
        registry_bytes = (json.dumps(registry, indent=2, sort_keys=True) + "\n").encode()
        registry_path.write_bytes(registry_bytes)
        evidence = json.loads(evidence_path.read_text())
        evidence["version"] = "1.9.0"
        evidence["sha256"]["registry.json"] = hashlib.sha256(registry_bytes).hexdigest()
        evidence_path.write_text(json.dumps(evidence))
        result = self.run_cli()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("unsupported", result.stderr.casefold())
        self.assertFalse(self.output.exists())


if __name__ == "__main__":
    unittest.main()
